server:
  port: 8100
spring:
  application:
    name: course-service
  data:
    mongodb:
      uri: mongodb+srv://admin:2lgiIC4opKrZ2jVR@cluster0.vzb0mdl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
