spring:
notification:
  mail:
    password: qvvo bnal rcle vqiv
    username: heshanthzimmendra@gmail.com
    cc: it21265242@my.sliit.lk
    bcc: newchattabotta@gmail.com


  text:
    number: +12513136047
    twillio_account_sid: AC0f2ece6f6a6093d75087ac58e978873c
    twillio_account_token: 5cd840031d94106e571aaaca8217b3d9

