server:
  port: 8765

spring:
  application:
    name: api-gateway

address:
  base:
    user-service: http://localhost:8000
    course-service: http://localhost:8100
    content-service: http://localhost:8200
    enrollment-service: http://localhost:8300

feign:
  user-service:
    name: user-service
    url: http://localhost:8000