server:
  port: 8000

spring:
  profiles:
    active: local
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://admin:zlwOj8Aqje5NxifT@cluster0.kdvjrko.mongodb.net/cluster0

jwt:
  signing:
    key: 413F4428472B4B6250655368566D5970337336763979244226452948404D6351
    expirationMs: 3600000

management:
  endpoint:
    health:
      probes:
        enabled: true
