name: Build, Push Docker Images, and Update Kubernetes Configurations

on:
  push:
    branches:
      - main
      - test/k8s-deployment

jobs:
  build_push_and_update_k8s:
    name: Build, Push and Update K8s Config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, course-content-service, course-service, enrollment-service, notification-service, payment-service, user-service]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            zulake/${{ matrix.service }}:${{ github.sha }}
            zulake/${{ matrix.service }}:latest
          cache-from: type=registry,ref=zulake/${{ matrix.service }}:latest
          cache-to: type=inline

      - name: Update Kubernetes Deployment Image Tag
        run: |
          service="${{ matrix.service }}"
          sed -i "s|image: zulake/$service:.*|image: zulake/$service:${{ github.sha }}|" ./kube-config/services/$service/deployment.yml

      - name: Commit and Push Changes to K8s Config Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add ./kube-config/services/${{ matrix.service }}/deployment.yml
          git commit -m "Update image tag for $service to ${{ github.sha }}"
          git push origin HEAD:${{ github.ref }}
