name: Build, Push Docker Images, and Update K8s Configs

on:
  push:
    branches:
      - main
      - test/k8s-deployment

jobs:
  build_and_push:
    name: Build and Push Service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, course-content-service, course-service, enrollment-service, notification-service, payment-service, user-service]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            zulake/${{ matrix.service }}:${{ github.sha }}
            zulake/${{ matrix.service }}:latest
          cache-from: type=registry,ref=zulake/${{ matrix.service }}:latest
          cache-to: type=inline
      - name: Update Kubernetes Deployment Image Tag
        run: |
          sed -i 's|image: zulake/${{ matrix.service }}:.*|image: zulake/${{ matrix.service }}:${{ github.sha }}|' ./kube-config/service/${{ matrix.service }}/deployment.yml
      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ./kube-config/service/${{ matrix.service }}/deployment.yml
          git commit -m "Update image tag for ${{ matrix.service }} to ${{ github.sha }}"
          git push
