name: Build and Push Docker Images to DockerHub

on:
  push:
    branches:
      - main
      - test/k8s-deployment

jobs:
  build_and_push:
    name: Build and Push Service
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, course-content-service, course-service, enrollment-service, notification-service, payment-service, user-service]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            zulake/${{ matrix.service }}:${{ github.sha }}
            zulake/${{ matrix.service }}:latest
          cache-from: type=registry,ref=zulake/${{ matrix.service }}:latest
          cache-to: type=inline
