name: Build, Push Docker Images, and Update Kubernetes Configurations

on:
  push:
    branches:
      - main
      - test/k8s-deployment

jobs:
  build_push_and_update_k8s:
    name: Build, Push and Update K8s Config
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [api-gateway, course-content-service, course-service, enrollment-service, notification-service, payment-service, user-service]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v3
        with:
          context: ./${{ matrix.service }}
          push: true
          tags: |
            zulake/${{ matrix.service }}:${{ github.sha }}
            zulake/${{ matrix.service }}:latest
          cache-from: type=registry,ref=zulake/${{ matrix.service }}:latest
          cache-to: type=inline

      - name: Update kube config
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git clone https://github.com/Y3S2-Semester/kube-config.git
          cd kube-config
          
          service="${{ matrix.service }}"
          sed -i "s|image: zulake/$service:.*|image: zulake/$service:${{ github.sha }}|" services/$service/deployment.yml
          
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          
          git config pull.ff only
          git add . && git commit -m "Synced $service kube config" || echo "No changes to commit"
          
          # Set remote with access token
          git remote set-url origin https://github.com/Y3S2-Semester/kube-config.git
          git remote set-url origin https://$ACCESS_TOKEN@github.com/Y3S2-Semester/kube-config.git
          
          n=0
          until [ "$n" -ge 3 ]
          do
            git pull --rebase && git push && break  # pushing to the default branch
            n=$((n+1))
            sleep 15
          done

        shell: bash
